app:
    build: .
    environment:
        REALM: prod
        REDIS_URL: "//redis:6379"
    links:
        - redis
    ports:
        - "8000:8000"
    # restart on reboot
    restart: always

redis:
    image: redis
